// 경기 이벤트 종류 (docs/02-architecture.md §8.3)
// 이벤트는 번역된 문장이 아니라 type + params 로 저장한다.
export enum RaceEventType {
  SessionStarted = "session_started",
  SessionRestarted = "session_restarted",
  SessionFinished = "session_finished",
  PositionChange = "position_change",
  Overtake = "overtake",
  PitStop = "pit_stop",
  FastestLap = "fastest_lap",
  PersonalBestLap = "personal_best_lap",
  GapClosing = "gap_closing",
  GapIncreasing = "gap_increasing",
  DrsRangeEntered = "drs_range_entered",
  YellowFlag = "yellow_flag",
  GreenFlag = "green_flag",
  SafetyCar = "safety_car",
  VirtualSafetyCar = "virtual_safety_car",
  RedFlag = "red_flag",
  Retirement = "retirement",
  StrategyNote = "strategy_note",
  // docs/10-race-events.md 신규 14종.
  // 기존 멤버의 값은 Firestore 에 저장된 이벤트와 호환을 위해 변경하지 않는다.
  Penalty = "penalty",
  Investigation = "investigation",
  TrackLimits = "track_limits",
  BlueFlag = "blue_flag",
  SectorYellow = "sector_yellow",
  SectorClear = "sector_clear",
  ChequeredFlag = "chequered_flag",
  DrsEnabled = "drs_enabled",
  DrsDisabled = "drs_disabled",
  TrackHazard = "track_hazard",
  PitLaneClosed = "pit_lane_closed",
  PitLaneOpen = "pit_lane_open",
  RainRisk = "rain_risk",
  TeamRadioPosted = "team_radio_posted",
}
